Add skipping pass prompt if no pass has been set

diff --git a/run_demo b/run_demo
--- a/run_demo
+++ b/run_demo
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
-. initialize
-
 # Clean-up after any disgraceful shutdown
 docker-compose down --remove-orphans
 
 # Start the server
-docker-compose up --detach cans-server || { echo "Starting the server failed" && exit 1; }
+docker-compose up --build --detach cans-server || { echo "Starting the server failed" && exit 1; }
 # Start the echo client
-docker-compose up --detach cans-echo-service || { \
+docker-compose up --build --detach cans-echo-service || { \
     echo "Starting the echo service failed" && docker-compose down && exit 1; \
 }
+
+. initialize
 
 python -m client
 
