Add more integration tests

diff --git a/run_alpha_demo b/run_alpha_demo
--- a/run_alpha_demo
+++ b/run_alpha_demo
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 # Start the server
-docker-compose up --detach cans-server || { echo "Starting the server failed" && exit 1; }
+docker-compose up --build --detach cans-server || { echo "Starting the server failed" && exit 1; }
 # Start the echo client
-docker-compose up --detach cans-echo-service || { \
+docker-compose up --build --detach cans-echo-service || { \
     echo "Starting the echo service failed" && docker-compose down && exit 1; \
 }
 
@@ -15,3 +15,5 @@ set +a
 export CANS_SERVER_HOSTNAME=localhost
 
 python -m client
+
+docker-compose down
